title: SideQuest
email: sidequest@merencia.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sidequestjs.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  sidequestjs
github_project: sidequestjs/sidequest
analytics_id: UA-40045005-5

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
    sass_dir: _scss
    style: :compressed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
